In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
from typing import Sequence
from langchain_openai import OpenAI
from langchain.output_parsers import PydanticOutputParser
from langchain.prompts import PromptTemplate
from pydantic import BaseModel
import json
import os, re
import win32com.client
from dotenv import load_dotenv
from docx import Document
from google import genai
from google.genai import types
import time

load_dotenv(".env")
API_KEY = os.getenv("GEMINI_API_KEY")
print(API_KEY)

client = genai.Client(
    api_key=API_KEY
)

df_jantung = pd.read_csv('cppt_jantung_extract.csv')
df_ranap = pd.read_csv('cppt_ranap_extract.csv')
df_remed = pd.read_csv('resume_medis_extract.csv')

df = pd.concat([df_jantung, df_ranap, df_remed], ignore_index=True)

AIzaSyDkjcpthVta8BbagC1l201c0YMSo2BfRNs

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

# --- Helper Functions ---

def parse_age(s):
    patt = re.compile(r'(?:(\d+)\s*thn)?\s*(?:(\d+)\s*bln)?\s*(?:(\d+)\s*hr)?', re.I)
    t, b, h = patt.fullmatch(s.strip()).groups()
    return int(t or 0), int(b or 0), int(h or 0)

def parse_age_column(df):
    tahun, bulan, hari = zip(*df['pasien.umur'].map(parse_age))
    df['age_days'] = np.array(tahun) * 365.25 + np.array(bulan) * 30.44 + np.array(hari)
    return df

def remove_age_outliers(df, lower, upper):
    return df[(df['age_days'] >= lower) & (df['age_days'] <= upper)]

def get_quota(df, max_total=1000, max_per_group=50):
    df = df.copy()
    df['pasien.jeniskelamin'] = df['pasien.jeniskelamin'].map({'Perempuan': 'F', 'Laki-Laki': 'M'})
    supply = df.pivot_table(index='grouped_diagnosa', columns='pasien.jeniskelamin', aggfunc='size', fill_value=0)
    flat_supply = {(diag, gender): count for diag, row in supply.iterrows() for gender, count in row.items()}
    sorted_supply = sorted(flat_supply.items(), key=lambda x: x[1], reverse=True)

    quota = {}
    used_f = 0
    used_m = 0
    max_per_gender = max_total // 2

    for (diag, gender), count in sorted_supply:
        if gender == 'F' and used_f >= max_per_gender:
            continue
        if gender == 'M' and used_m >= max_per_gender:
            continue
        available_quota = min(count, max_per_group)
        if gender == 'F':
            take = min(available_quota, max_per_gender - used_f)
            used_f += take
        else:
            take = min(available_quota, max_per_gender - used_m)
            used_m += take
        if take > 0:
            quota[(diag, gender)] = take
        if used_f + used_m >= max_total:
            break
    return quota

def draw_quota_sample(df, quota, on=['grouped_diagnosa', 'pasien.jeniskelamin']):
    out = []
    for key, n in quota.items():
        gdf = df
        for col, val in zip(on, key):
            gdf = gdf[gdf[col] == val]
        if len(gdf) >= n:
            out.append(gdf.sample(n, random_state=0))
    if not out:
        print("⚠️ No groups met the quota requirements.")
        return pd.DataFrame()  # return empty safely
    return pd.concat(out, ignore_index=True)

In [3]:
df2 = df.copy()
df2 = parse_age_column(df2)

# Step 1: Visualize scatter or histogram
# plt.figure(figsize=(10, 5))
# sns.histplot(df2['age_days'], bins=50, kde=True)
# plt.title("Age Distribution (in days)")
# plt.xlabel("Age (days)")
# plt.ylabel("Count")
# plt.show()

# Step 2: Remove outliers
df_clean = remove_age_outliers(df2, 365, 28000)

# plt.figure(figsize=(10, 5))
# sns.histplot(df_clean['age_days'], bins=50, kde=True, color='skyblue')
# plt.title("Cleaned Age Distribution (in days)")
# plt.xlabel("Age (days)")
# plt.ylabel("Frequency")
# plt.grid(True)
# plt.show()



import pandas as pd
import numpy as np

# Copy and map gender to F/M
df = df_clean.copy()
df['pasien.jeniskelamin'] = df['pasien.jeniskelamin'].map({
    'Perempuan': 'F',
    'Laki-Laki': 'M'
})

# Build supply table: diagnosis × gender
supply = df.pivot_table(
    index='grouped_diagnosa',
    columns='pasien.jeniskelamin',
    aggfunc='size',
    fill_value=0
)

# Flatten supply into a dict: (diagnosis, gender) → available_count
flat_supply = {
    (diag, gender): count
    for diag, row in supply.iterrows()
    for gender, count in row.items()
}

# Sort by highest available counts
sorted_supply = sorted(flat_supply.items(), key=lambda x: x[1], reverse=True)

# Set limits
max_total = 3000
max_per_gender = max_total // 2  # 500 each
max_per_group = 50               # cap per diagnosis+gender group

# Create quota dictionary and gender counters
quota = {}
used_f = 0
used_m = 0

for (diag, gender), count in sorted_supply:
    # Skip if gender already reached cap
    if gender == 'F' and used_f >= max_per_gender:
        continue
    if gender == 'M' and used_m >= max_per_gender:
        continue

    # Determine how many to take from this group
    available_quota = min(count, max_per_group)
    if gender == 'F':
        take = min(available_quota, max_per_gender - used_f)
        used_f += take
    else:
        take = min(available_quota, max_per_gender - used_m)
        used_m += take

    if take > 0:
        quota[(diag, gender)] = take

    # Stop if total quota reached
    if used_f + used_m >= max_total:
        break

# Sampling function
def draw_exact(df, quota, on):
    out = []
    for key, n in quota.items():
        gdf = df
        for col, val in zip(on, key):
            gdf = gdf[gdf[col] == val]
        if len(gdf) < n:
            continue  # skip if not enough data
        out.append(gdf.sample(n, random_state=0))
    return pd.concat(out, ignore_index=True)

# Draw final balanced dataset
df_final = draw_exact(df, quota, ['grouped_diagnosa', 'pasien.jeniskelamin'])

# Final stats
print("shape:", df_final.shape)
print("Female:", (df_final['pasien.jeniskelamin'] == 'F').sum())
print("Male:", (df_final['pasien.jeniskelamin'] == 'M').sum())
print("Diagnosa:", df_final.groupby('grouped_diagnosa').size())

tahun, bulan, hari = zip(*df_final['pasien.umur'].map(parse_age))
df_final['age_days'] = np.array(tahun)*365.25 + np.array(bulan)*30.44 + np.array(hari)
cut_tuamuda = 49.53 * 365.25            
bins   = [0, cut_tuamuda, np.inf]    
labels = ['muda', 'tua']
df_final['age_cat2'] = pd.cut(df_final['age_days'], bins=bins, labels=labels, right=True)

df_final.groupby('age_cat2').size()

shape: (3000, 26)
Female: 1500
Male: 1500
Diagnosa: grouped_diagnosa
Angina Pectoris                       100
Atherosclerosis Heart Disease         100
Atrial Fibrillation                   100
Cardiomiopathy                         50
Chest Pain                            100
Chronic Heart Failure                 100
Coronary Artery Disease               100
Hipertensi                            100
Hypertensive Heart Disease            100
Mitral Regurgitation                   50
Mitral Stenosis                        50
Takikardia                             50
abses                                  50
anemia                                100
bronkopneumonia                        50
chronic kidney disease                100
coronary artery disease                50
dengue fever                          100
diabetes mellitus                     100
dyspepsia                              50
febris                                100
fraktur                               100
gastroenteritis                       100
hernia                                 50
hipoalbumin                            50
impaksi                               100
infeksi bakteri                       100
infeksi saluran kemih                  50
kolelitiasis                           50
pneumonia                             100
respiratory failure                   100
skizophrenia                           50
st-elevation myocardial infarction     50
stroke infark                         100
tuberkulosis                          100
tumor                                 100
viral Infection                       100
dtype: int64

C:\Users\asus\AppData\Local\Temp\ipykernel_1876\2836632656.py:114: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_final.groupby('age_cat2').size()

age_cat2
muda    1500
tua     1500
dtype: int64

In [4]:
df_final = df_final.reset_index()
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   index                                3000 non-null   int64
 1   Unnamed: 0                           3000 non-null   int64
 2   O                                    998 non-null    object
 3   S                                    982 non-null    object
 4   P                                    596 non-null    object
 5   grouped_diagnosa                     3000 non-null   object
 6   diagnosaDokter[0].keterangan         3000 non-null   object
 7   icd10_label                          2727 non-null   object
 8   pasien.jeniskelamin                  3000 non-null   object
 9   pasien.umur                          3000 non-null   object
 10  registrasi.kelompokpasien            3000 non-null   object
 11  registrasi.namakelas                 3000 non-null   object
 12  icd9_label                           1899 non-null   object
 13  detailTindakan[0].ketTindakanDokter  1792 non-null   object
 14  tinggiBadan                          600 non-null    object
 15  beratBadan                           831 non-null    object
 16  tekananDarah                         1718 non-null   object
 17  nadi                                 1952 non-null   object
 18  suhu                                 1796 non-null   object
 19  pernapasan                           1925 non-null   object
 20  SPO2                                 1465 non-null   object
 21  terapi                               1956 non-null   object
 22  riwayatPenyakit                      1994 non-null   object
 23  pemeriksaanFisikLain                 1696 non-null   object
 24  pemeriksaPenunjang                   1866 non-null   object
 25  hasilIntruksi                        1639 non-null   object
 26  age_days                             3000 non-null   float64
 27  age_cat2                             3000 non-null   category
dtypes: category(1), float64(1), int64(2), object(24)
memory usage: 636.0+ KB

In [5]:
# df_o_notna = df_final[df_final['O'].notna()].copy()

# chunk_size = 50
# chunks = [df_o_notna.iloc[i:i + chunk_size] for i in range(0, len(df_o_notna), chunk_size)]

# processed_chunks = []
# print(len(chunks))

In [6]:
# xx = 20

# df = chunks[xx].copy()
# cols = ['nadi', 'suhu','pernapasan','SPO2','tinggiBadan', 'beratBadan','tekananDarah']
# extracted_rows = []

# for index, row in df.iterrows():
#     time.sleep(5)

#     extracted = {"index": row["index"]}
#     print(index)

#     raw_text = row['O']
#     if pd.isna(raw_text) or not isinstance(raw_text, str) or raw_text.strip() == "":
#         continue

#     # Create a specific prompt for each column
#     prompt_text = f"""
#         Ekstrak 'nadi', 'suhu','pernapasan','SPO2','tinggiBadan', 'beratBadan','tekananDarah' dari teks di bawah ini.
#         Berikan hasilnya dalam format JSON tanpa tambahan teks atau penjelasan.

#         Teks:
#         \"{raw_text.strip()}\"
#         """


#     try:
#         model = "gemini-2.0-flash"
#         contents = [
#             types.Content(
#                 role="user",
#                 parts=[
#                     types.Part.from_text(text=prompt_text),
#                 ],
#             ),
#         ]
#         generate_content_config = types.GenerateContentConfig(
#             response_mime_type="text/plain",
#         )

#         response_text=""
#         for chunk in client.models.generate_content_stream(
#             model=model,
#             contents=contents,
#             config=generate_content_config,
#         ): response_text += chunk.text

#         print(response_text)

#         clean_text = re.sub(r"```json|```", "", response_text).strip()
#         xdata = json.loads(clean_text)
#         extracted[f"O_extracted"] = xdata

#     except Exception as e:
#         print(f"Row {index} - Error processing column :", e)
#         extracted[f"O_extracted"] = None

#     extracted_rows.append(extracted)

In [7]:
# print(extracted_rows)

In [8]:
# dff = pd.DataFrame(extracted_rows)
# dff.head()

# dff.to_csv(f"./data_extract/extract{xx}.csv")

In [9]:
gabungan_df = pd.DataFrame([])

for i in range(20):
    inputdf = pd.read_csv(f'./data_extract/extract{i}.csv')
    gabungan_df = pd.concat([gabungan_df, inputdf], ignore_index=True)

gabungan_df.tail()

     Unnamed: 0  index                                        O_extracted
993          43   2995  {'nadi': '73 x/mnt', 'suhu': '36 °C', 'pernapa...
994          44   2996  {'nadi': '70 x/mnt', 'suhu': '36 °C', 'pernapa...
995          45   2997  {'nadi': '74 x/mnt', 'suhu': '36 °C', 'pernapa...
996          46   2998  {'nadi': '71 x/mnt', 'suhu': '36 °C', 'pernapa...
997          47   2999  {'nadi': '53 x/mnt', 'suhu': '36 °C', 'pernapa...

In [10]:
import ast
def safe_eval(x):
    if pd.isna(x):
        return {}
    try:
        return ast.literal_eval(x)
    except Exception:
        return {}

# Parse each row safely
df_parsed = gabungan_df['O_extracted'].apply(safe_eval).apply(pd.Series)

# Merge result
gabungan_df = pd.concat([gabungan_df, df_parsed], axis=1)

gabungan_df

,Unnamed: 0,index,O_extracted,nadi,suhu,pernapasan,SPO2,tinggiBadan,beratBadan,tekananDarah
0,0,0,"{'nadi': '71 x/mnt', 'suhu': '36 °C', 'pernapa...",71 x/mnt,36 °C,20 x/mnt,None,None,None,169/94 mmHg
1,1,1,"{'nadi': '56 x/mnt', 'suhu': '36 °C', 'pernapa...",56 x/mnt,36 °C,20 x/mnt,None,None,None,154/97 mmHg
2,2,2,"{'nadi': '70 x/mnt', 'suhu': '36 °C', 'pernapa...",70 x/mnt,36 °C,20 x/mnt,None,None,None,140/85 mmHg
3,3,3,"{'nadi': '89 x/mnt', 'suhu': '36 °C', 'pernapa...",89 x/mnt,36 °C,20 x/mnt,None,165 Cm,65 Kg,103/66 mmHg
4,4,4,"{'nadi': '53 x/mnt', 'suhu': '36 °C', 'pernapa...",53 x/mnt,36 °C,20 x/mnt,None,None,None,136/70 mmHg
...,...,...,...,...,...,...,...,...,...,...
993,43,2995,"{'nadi': '73 x/mnt', 'suhu': '36 °C', 'pernapa...",73 x/mnt,36 °C,20 x/mnt,None,None,None,114/80 mmHg
994,44,2996,"{'nadi': '70 x/mnt', 'suhu': '36 °C', 'pernapa...",70 x/mnt,36 °C,20 x/mnt,None,None,None,138/79 mmHg
995,45,2997,"{'nadi': '74 x/mnt', 'suhu': '36 °C', 'pernapa...",74 x/mnt,36 °C,20 x/mnt,NaN,NaN,NaN,124/80 mmHg
996,46,2998,"{'nadi': '71 x/mnt', 'suhu': '36 °C', 'pernapa...",71 x/mnt,36 °C,20 x/mnt,None,None,None,130/89 mmHg
997,47,2999,"{'nadi': '53 x/mnt', 'suhu': '36 °C', 'pernapa...",53 x/mnt,36 °C,20 x/mnt,None,None,None,131/62 mmHg

In [11]:
columns_to_replace = ['nadi', 'suhu', 'pernapasan', 'SPO2', 'tinggiBadan', 'beratBadan', 'tekananDarah']

df_final.update(gabungan_df[columns_to_replace])

df_final.info()

df_final.to_csv("withO_3000_gabungan.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 28 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   index                                3000 non-null   int64
 1   Unnamed: 0                           3000 non-null   int64
 2   O                                    998 non-null    object
 3   S                                    982 non-null    object
 4   P                                    596 non-null    object
 5   grouped_diagnosa                     3000 non-null   object
 6   diagnosaDokter[0].keterangan         3000 non-null   object
 7   icd10_label                          2727 non-null   object
 8   pasien.jeniskelamin                  3000 non-null   object
 9   pasien.umur                          3000 non-null   object
 10  registrasi.kelompokpasien            3000 non-null   object
 11  registrasi.namakelas                 3000 non-null   object
 12  icd9_label                           1899 non-null   object
 13  detailTindakan[0].ketTindakanDokter  1792 non-null   object
 14  tinggiBadan                          693 non-null    object
 15  beratBadan                           924 non-null    object
 16  tekananDarah                         2133 non-null   object
 17  nadi                                 2307 non-null   object
 18  suhu                                 2182 non-null   object
 19  pernapasan                           2273 non-null   object
 20  SPO2                                 1466 non-null   object
 21  terapi                               1956 non-null   object
 22  riwayatPenyakit                      1994 non-null   object
 23  pemeriksaanFisikLain                 1696 non-null   object
 24  pemeriksaPenunjang                   1866 non-null   object
 25  hasilIntruksi                        1639 non-null   object
 26  age_days                             3000 non-null   float64
 27  age_cat2                             3000 non-null   category
dtypes: category(1), float64(1), int64(2), object(24)
memory usage: 636.0+ KB

In [2]:
df_final = pd.read_csv('withO_3000_gabungan.csv')

chunk_size = 50
chunks = [df_final.iloc[i:i + chunk_size] for i in range(0, len(df_final), chunk_size)]

processed_chunks = []
print(len(chunks))

60

In [15]:
xx = 8

df = chunks[xx].copy()
extracted_rows = []

for index, row in df.iterrows():
    time.sleep(5)

    extracted = {"index": row["index"]}
    print(index)

    raw_text = row['S']
    if pd.isna(raw_text) or not isinstance(raw_text, str) or raw_text.strip() == "":
        raw_text = row['riwayatPenyakit']
        if pd.isna(raw_text) or not isinstance(raw_text, str) or raw_text.strip() == "":
            continue

    # Create a specific prompt for each column
    prompt_text = f"""
        Ekstrak semua keluhan utama secara eksplisit dari teks berikut.
        - Hanya ekstrak yang jelas disebutkan dalam teks.
        - Gunakan format JSON dengan satu key: "keluhan_utama".
        - Nilai dari "keluhan_utama" adalah array berisi string keluhan.
        - Jika tidak ada keluhan, isi array dengan satu item: "Tidak ada keluhan".
        - Jangan tambahkan teks atau penjelasan di luar JSON.

        Teks:
        \"{raw_text.strip()}\"
        """


    try:
        model = "gemini-2.0-flash"
        contents = [
            types.Content(
                role="user",
                parts=[
                    types.Part.from_text(text=prompt_text),
                ],
            ),
        ]
        generate_content_config = types.GenerateContentConfig(
            response_mime_type="text/plain",
        )

        response_text=""
        for chunk in client.models.generate_content_stream(
            model=model,
            contents=contents,
            config=generate_content_config,
        ): response_text += chunk.text

        print(response_text)

        clean_text = re.sub(r"```json|```", "", response_text).strip()
        xdata = json.loads(clean_text)
        extracted[f"keluhan_extracted"] = xdata

    except Exception as e:
        print(f"Row {index} - Error processing column :", e)
        extracted[f"keluhan_extracted"] = None

    extracted_rows.append(extracted)

400
```json
{
  "keluhan_utama": [
    "sesak",
    "batuk berdahak",
    "demam naik-turun"
  ]
}
```
401
```json
{
  "keluhan_utama": [
    "lemas lunglai",
    "BAB cair berisi darah (+) ampas (+) tanpa lendir",
    "muntah",
    "kejang",
    "demam",
    "batuk"
  ]
}
```
402
Row 402 - Error processing column : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-flash'}, 'quotaValue': '200'}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '29s'}]}}
403
Row 403 - Error processing column : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-flash'}, 'quotaValue': '200'}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '23s'}]}}
404
Row 404 - Error processing column : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-flash'}, 'quotaValue': '200'}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}
405
Row 405 - Error processing column : 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.0-flash'}, 'quotaValue': '200'}]}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '13s'}]}}

KeyboardInterrupt:

In [ ]:
print(extracted_rows)

[{'index': 350, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'batuk']}}, {'index': 351, 'keluhan_extracted': {'keluhan_utama': ['batuk berdarah 1minggu', 'batuk lebih dari 2 minggu', 'lemas', 'sesak']}}, {'index': 352, 'keluhan_extracted': {'keluhan_utama': ['Batuk berdahak', 'Demam']}}, {'index': 353, 'keluhan_extracted': {'keluhan_utama': ['demam 7 hari SMRS', 'nyeri kepala (+)', 'lemas (+)', 'batuk berdahak (+)']}}, {'index': 354, 'keluhan_extracted': {'keluhan_utama': ['sesak napas', 'sering terbangun malam hari karena sesak', 'terkdang muncul mengi saat sesak napas']}}, {'index': 355, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'batuk berdahak hijau']}}, {'index': 356, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'demam', 'batuk', 'pilek']}}, {'index': 357, 'keluhan_extracted': {'keluhan_utama': ['demam sejak 2 hari', 'kejang', 'sesak nafas (+)', 'BAB cair yang hilang timbul selama 4 bulan', 'bengkak pada kedua tungkainya']}}, {'index': 358, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'mengi', 'bersin', 'batuk']}}, {'index': 359, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk pilek', 'mual muntah', 'nafsu makan turun']}}, {'index': 360, 'keluhan_extracted': {'keluhan_utama': ['Sakit kepala bagian belakang', 'Muntah', 'Lemas', 'Kepala terasa berputar', 'Mual']}}, {'index': 361, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk', 'nafsu makan turun', 'mata pasien tiba-tiba mendelik ke atas']}}, {'index': 362, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'demam', 'sesak nafas', 'mencret']}}, {'index': 363, 'keluhan_extracted': {'keluhan_utama': ['demam', 'muntah', 'lemas']}}, {'index': 364, 'keluhan_extracted': {'keluhan_utama': ['demam', 'mual muntah', 'bab cair', 'batuk', 'pilek']}}, {'index': 365, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk dahak', 'keluar melalui muntah', 'pilek']}}, {'index': 366, 'keluhan_extracted': {'keluhan_utama': ['demam', 'bab cair', 'mual muntah', 'nyeri tenggorokan', 'batuk pilek']}}, {'index': 367, 'keluhan_extracted': {'keluhan_utama': ['sesak nafas', 'batuk', 'muntah', 'demam', 'mual muntah', 'nafsu makan berkurang']}}, {'index': 368, 'keluhan_extracted': {'keluhan_utama': ['demam', 'lemas', 'nyeri ulu hati', 'mual', 'muntah', 'batuk berdahak', 'sesak']}}, {'index': 369, 'keluhan_extracted': {'keluhan_utama': ['demam', 'sesak nafas', 'batuk', 'mual', 'bab cair', 'BB sulit naik']}}, {'index': 370, 'keluhan_extracted': {'keluhan_utama': ['Sesak', 'Batuk', 'Demam', 'Pusing']}}, {'index': 371, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'batuk berdahak', 'BAK sulit harus mengedan', 'BAK kadang macet']}}, {'index': 372, 'keluhan_extracted': {'keluhan_utama': ['Sesak Nafas cepat dan dalam', 'Batuk', 'lemas']}}, {'index': 373, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'menangis setelah kejang', 'demam', 'batuk']}}, {'index': 374, 'keluhan_extracted': {'keluhan_utama': ['sesak nafas', 'batuk', 'pilek', 'demam', 'bab cair', 'lendir', 'muntah', 'mencret', 'tumbuh kembang tidak sesuai dengan usianya']}}, {'index': 375, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'batuk']}}, {'index': 376, 'keluhan_extracted': {'keluhan_utama': ['sesak memberat', 'lemas', 'kembung', 'nyeri perut', 'demam', 'batuk', 'muntah darah']}}, {'index': 377, 'keluhan_extracted': {'keluhan_utama': ['demam hilang timbul', 'keringat dingin malam hari', 'penurunan berat badan', 'lemas', 'mual muntah', 'penurunan nafsu makan']}}, {'index': 378, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'demam', 'batuk pilek']}}, {'index': 379, 'keluhan_extracted': {'keluhan_utama': ['demam', 'mual muntah', 'kepala pusing', 'lemas', 'batuk berdahak']}}, {'index': 380, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk pilek', 'sulit makan minum', 'terlihat lemas', 'muncul bintik merah pada kaki tangan dan mulut']}}, {'index': 381, 'keluhan_extracted': {'keluhan_utama': ['batuk', 'batuk dahak wara hijau', 'demam hilang timbul', 'tenggorkoan sakit hingga sulit makan']}}, {'index': 382, 'keluhan_extracted': {'keluhan_utama': ['demam 3 hari smrs', 'mual', 'muntah', 'intake sedikit', 'batuk']}}, {'index': 383, 'keluhan_extracted': {'keluhan_utama': ['sesak nafas', 'perut membesar', 'nyeri', 'batuk', 'penurunan BB', 'BAB hitam', 'makan minum menurun']}}, {'index': 384, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk ngogrok', 'tidak mau makan']}}, {'index': 385, 'keluhan_extracted': {'keluhan_utama': ['demam 7 hari smrs', 'batuk berdahak', 'sesak napas', 'bab cair', 'nyeri ulu hati']}}, {'index': 386, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'Demam hilang timbul', 'Batuk pileh']}}, {'index': 387, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk', 'nafsu makan turun', 'mual muntah', 'gatal', 'terdapat luka pada selangkangan dan paha']}}, {'index': 388, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk', 'sesan nafas', 'muntah', 'bab cair', 'lemas', 'kejang']}}, {'index': 389, 'keluhan_extracted': {'keluhan_utama': ['sesak nafas', 'batuk', 'demam']}}, {'index': 390, 'keluhan_extracted': {'keluhan_utama': ['Sesak yang memberat sejak 3 hari SMRS', 'Batuk sejak 1 bulan', 'Batuk berdahak (+) hijau kadang putih', 'bb menurun 10 kg dalam 1 bulan', 'Tidak nafsu makan (+)', 'Merasa menggigil (+) tiap malam', 'Mual (+)']}}, {'index': 391, 'keluhan_extracted': {'keluhan_utama': ['nyeri perut', 'perut membesar', 'mual', 'mata kuning', 'BAB tidak lancar']}}, {'index': 392, 'keluhan_extracted': {'keluhan_utama': ['kejang', 'sesak nafas', 'batuk']}}, {'index': 393, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk pilek', 'batuk berdahak', 'sulit mengeluarkan dahak', 'terkadang saat tidur terdengar suara grok-grok']}}, {'index': 394, 'keluhan_extracted': {'keluhan_utama': ['sesak napas', 'demam menggigil', 'batuk darah']}}, {'index': 395, 'keluhan_extracted': {'keluhan_utama': ['sesak', 'batuk', 'keringat dingin', 'lemas', 'mual', 'suara serak']}}, {'index': 396, 'keluhan_extracted': {'keluhan_utama': ['sesak napas', 'batuk terus menerus', 'dahak bening kekuningan', 'demam', 'badan lemas', 'tidak mau makan dan minum']}}, {'index': 397, 'keluhan_extracted': {'keluhan_utama': ['batuk', 'sesak', 'nyeri ulu hati']}}, {'index': 398, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk', 'pilek', 'nafsu makan turun']}}, {'index': 399, 'keluhan_extracted': {'keluhan_utama': ['demam', 'batuk', 'muntah']}}]

In [ ]:
dff = pd.DataFrame(extracted_rows)
dff.head()

dff.to_csv(f"./keluhan_extract_done/extract{xx}.csv")